#!/bin/bash

set -e

if ! which silver > /dev/null; then
  echo "Requires a silver installation to use. ('silver' should be in PATH)"
  echo "See https://github.com/melt-umn/silver/"
  echo "Or http://melt.cs.umn.edu/ for more information."
  exit 1
fi

ARGS=$@

if [[ -d "$ABLEC_BASE" ]]; then
  echo "Found AbleC at $ABLEC_BASE"
elif [[ -d ../ableC ]]; then
  echo "Found AbleC at ../ableC"
  ABLEC_BASE=../ableC
else
  echo "Did not spot AbleC, build will likely fail."
fi

ARGS="$ARGS -I $ABLEC_BASE/grammars"

silver $ARGS edu:umn:cs:melt:ableP:artifacts:promelaCore
silver $ARGS edu:umn:cs:melt:ableP:artifacts:promelaCore:tests
(cd edu.umn.cs.melt.ableP/artifacts/promelaCore/tests && java -jar ../../../../edu.umn.cs.melt.ableP.artifacts.promelaCore.tests.jar)
silver $ARGS edu:umn:cs:melt:ableP:artifacts:promela
silver $ARGS edu:umn:cs:melt:ableP:artifacts:promela:tests
(cd edu.umn.cs.melt.ableP/artifacts/promela/tests && java -jar ../../../../edu.umn.cs.melt.ableP.artifacts.promela.tests.jar)
silver $ARGS edu:umn:cs:melt:ableP:artifacts:aviation
silver $ARGS edu:umn:cs:melt:ableP:artifacts:aviation:tests
(cd edu.umn.cs.melt.ableP/artifacts/aviation/tests && java -jar ../../../../edu.umn.cs.melt.ableP.artifacts.aviation.tests.jar)

echo "Success"

