#!/bin/bash

### Step 1.   Copy into a release branch in Subversion !

echo "Making initial tar file"
tar cf ableP.tar  \
  "--exclude=.svn" "--exclude=tests" "--exclude=XX" \
  "--exclude=syntax_check" \
  "--exclude=docs" \
  "--exclude=Others"   "--exclude=Notes.txt*" \
  "--exclude=build.xml" \
  "--exclude=*.svX" \
  "--exclude=*.test"  "--exclude=*.test.output" \
  "--exclude=*.tar" "--exclude=*.jar" \
  "--exclude=ToDo" "--exclude=ReleaseTest" \
  ableP || exit
echo "Creating directory for release"
mkdir -p ReleaseTest
rm -Rf ReleaseTest/*

mv ableP.tar ReleaseTest || exit
cd ReleaseTest
tar xf ableP.tar || exit
mv ableP.tar first_ableP.tar || exit
cd ableP
echo "#1: `pwd`"


### Step 2.   Run this script in the release branch.

# ./cleanup

if [ -z "$1" ]; then
  echo "invoke make-dist with a version argument."
  echo "For example:  ./make-dist 0.3.1-rc1"
  exit 1
fi

find . -name "*.sv" \! -name "ConcreteSyntax.sv" -print -exec ./addLGPLheader {} \;

echo "DONE"

ABLEP="ableP-$1"

if [[ -a $ABLEP || -a $ABLEP.tar.gz ]]; then
  echo "error: $ABLEP already exists?"
  exit 1
fi

cd ..

#ln -s . $ABLEP

tar zcvf $ABLEP.tar.gz \
 "--exclude=.svn" "--exclude=*~" "--exclude=syntax_check" \
 "--exclude=addLGPLheader" \
 "--exclude=makedist" \
 "--exclude=cleanup" \
 "--exclude=lgpl_header.txt" \
 ableP

# $ABLEP/artifacts/ \
# $ABLEP/host/ \
# $ABLEP/extensions/
# $ABLEP/COPYING \
# $ABLEP/COPYING.LESSER \
# $ABLEP/HISTORY \
# $ABLEP/README.txt \
# $ABLEP/INSTALL \
 
#rm $ABLEP

