#!/bin/bash

#silver.copper --onlycs edu:umn:cs:melt:ableJ14:host 

#silver.copper --onlycs edu:umn:cs:melt:ableJ14:exts:foreach

#java -classpath \
#  /project/melt/People/evw/Melt/Copper/CopperCompiler.jar edu/umn/cs/melt/copper/main/ParserCompiler -compose None None \
#  .Generated/Module_edu_umn_cs_melt_ableJ14_host_Grammar.copper  \
#  .Generated/Module_edu_umn_cs_melt_ableJ14_exts_foreach_Grammar.copper  > /dev/null



# This script will use Silver to build an AG evaluator for the
# tutorials grammar and run ant to compile the resulting Java code.

# invoke as               ./silver-compile
# or add arguments, like  ./silver-compile --clean

export GRAMMAR_PATH="../../../../../../../../../grammars"
export  SILVER_HOME="../../../../../../../../../silver/trunk/jars"

export ANT_OPTS="-Xss32m -Xmx2000m"

java -Xss8M -Xmx2000M -jar $SILVER_HOME/RunSilver.jar \
     edu:umn:cs:melt:ableP:extensions:syntax_check:ext

