#!/bin/bash

echo "Attempting to run modular determinism analysis for tables extension."

export GRAMMAR_PATH="../../../../../../../../grammars"
export  SILVER_HOME="../../../../../../../../silver/trunk"

echo ""
echo "First, create the .copper spec for the host language parser"
echo ""

cd $GRAMMAR_PATH/edu/umn/cs/melt/ableP/artifacts/promela
./silver-compile --clean

cp $SILVER_HOME/generated/src/edu/umn/cs/melt/ableP/host/hostParser/Parser_edu_umn_cs_melt_ableP_host_hostParser_promelaParser.copper  .

cd $GRAMMAR_PATH/edu/umn/cs/melt/ableP/extensions/syntax_check

echo ""
echo "Second, create the .copper spec for the extension"
echo ""

export ANT_OPTS="-Xss32m -Xmx2000m"

java -Xss8M -Xmx2000M -jar $SILVER_HOME/jars/RunSilver.jar \
     edu:umn:cs:melt:ableP:extensions:syntax_check

cp $SILVER_HOME/generated/src/edu/umn/cs/melt/ableP/extensions/syntax_check/Parser_edu_umn_cs_melt_ableP_extensions_syntax_check_extGrammar.copper .

echo ""
echo "Third, run the modular determinism test" 
echo ""

java -Xss8M -Xmx2000M -jar $SILVER_HOME/jars/CopperCompiler.jar -compose \
  Parser_edu_umn_cs_melt_ableP_host_hostParser_promelaParser.copper \
  Parser_edu_umn_cs_melt_ableP_extensions_syntax_check_extGrammar.copper \
  > Parse.java  
