#!/bin/bash

# This script will use Silver to build an AG evaluator for the
# tutorials grammar and run ant to compile the resulting Java code.

# invoke as               ./silver-compile
# or add arguments, like  ./silver-compile --clean

export GRAMMAR_PATH="../../../../../../../../../grammars"
export  SILVER_HOME="../../../../../../../../../silver/trunk"

export ANT_OPTS="-Xss32m -Xmx2000m"

java -Xss8M -Xmx1000M -jar $SILVER_HOME/jars/RunSilver.jar \
     $1 -o ableP.tests.jar \
     edu:umn:cs:melt:ableP:artifacts:promelaCore:tests \
     && ant

#silver $@ -o ableP.tests.jar \
#     edu:umn:cs:melt:ableP:artifacts:promelaCore:tests \

