// Promela code generated by ableP.


active proctype main () 
{
  int i;
 i = 4 ;

do
 ::     goto l4 ;
 :: (i < 10) ;

    i = (i + 1) ;

 od ;

l4: 1 ;

 printf ("The selection is: %d\n", i);

}
//end
