#!/bin/bash

# invoke as               ./silver-compile
# or add arguments, like  ./silver-compile --clean

export GRAMMAR_PATH="../../../../../../.."

silver -o ableP.aviation.jar $@ edu:umn:cs:melt:ableP:artifacts:aviation

