#!/bin/bash

# This script will use Silver to build an AG evaluator for the
# tutorials grammar and run ant to compile the resulting Java code.

# invoke as               ./silver-compile
# or add arguments, like  ./silver-compile --clean

export GRAMMAR_PATH="../../../../../../../../grammars"
#export  SILVER_HOME="../../../../../../../../silver/trunk/jars"

export ANT_OPTS="-Xss32m -Xmx2000m"

java -Xss8M -Xmx2000M -jar $SILVER_HOME/RunSilver.jar \
     $1 -o ableP.promela.jar \
     edu:umn:cs:melt:ableP:artifacts:promela \
     && ant
